variable "domain" {}
variable "certificate_arn" {}
variable "document_root" {}
variable "enabled" {}
variable "route53_zone_id" {}
variable "aws_region" {}
variable "access_key" {}
variable "secret_key" {}
variable "cache_ttl" {}
